require "svgen/nestable"
require "svgen/svg"
require "svgen/element/group"
require "svgen/element/rect"
require "svgen/element/circle"
require "svgen/element/text"
require "svgen/element/line"
require "svgen/element/path"
